export const company = {
  name: 'Surfers Paradise',
  slogan: '20 anos no mercado de acessórios e equipamentos para o Surf',
  cnpj: '',
  email: 'contato@surfersparadise.com.br',
  phone: '(11) 94716-9003',
  whatsapp: '5511947169003',
  address: {
    street: 'Alameda dos Maracatins',
    number: '1317',
    complement: '',
    neighborhood: 'Indianópolis',
    city: 'São Paulo',
    state: 'SP',
    cep: '04089-014',
  },
  social: {
    instagram: 'https://www.instagram.com/lojasurfersparadiseoficial/',
    facebook: 'https://web.facebook.com/lojasurfersparadise/',
    youtube: '',
  },
  businessHours: 'Seg a Sex: 10h às 20h | Sáb: 10h às 19h | Dom: Fechado',
  url: 'https://surfersparadise.com.br',
  orderPrefix: 'SP',
  payment: {
    maxInstallments: 10,
    minInstallmentValue: 30,
    pixDiscountPercent: 10,
    boletoDiscountPercent: 10,
  },
  shipping: {
    freeShippingMinValue: 299.9,
    originCep: '04089-014',
  },
} as const;
